from app.users.accounts import DEMO_USERS, DemoUserDefinition, UserAccount, UserSession
from app.users.permissions import (
    BACKUP_DATABASE,
    CONTROL_MONITORING,
    CHANGE_OPERATING_MODE,
    CREATE_SHIFT_ENTRY,
    CREATE_SHIFT_HANDOVER,
    IMPORT_PROCESS_DATA,
    MANAGE_USERS,
    RESET_EMERGENCY,
    RESET_EQUIPMENT_STATUSES,
    SIMULATE_EMERGENCY,
    VIEW_DATABASE_STATISTICS,
    VIEW_DEVIATIONS,
    VIEW_DIAGNOSTICS,
    VIEW_EQUIPMENT,
    VIEW_FORECASTING,
    VIEW_LOGS,
    VIEW_MONITORING,
    VIEW_REPORTS,
    VIEW_RESOURCES,
    VIEW_SHIFT_JOURNAL,
    get_accessible_tabs,
    get_permissions_for_role,
    has_permission,
)
from app.users.roles import RoleDefinition, get_role_definitions
from app.users.security import hash_password

__all__ = [
    "BACKUP_DATABASE",
    "CONTROL_MONITORING",
    "CHANGE_OPERATING_MODE",
    "CREATE_SHIFT_ENTRY",
    "CREATE_SHIFT_HANDOVER",
    "DEMO_USERS",
    "IMPORT_PROCESS_DATA",
    "MANAGE_USERS",
    "RESET_EMERGENCY",
    "RESET_EQUIPMENT_STATUSES",
    "SIMULATE_EMERGENCY",
    "VIEW_DATABASE_STATISTICS",
    "VIEW_DEVIATIONS",
    "VIEW_DIAGNOSTICS",
    "VIEW_EQUIPMENT",
    "VIEW_FORECASTING",
    "VIEW_LOGS",
    "VIEW_MONITORING",
    "VIEW_REPORTS",
    "VIEW_RESOURCES",
    "VIEW_SHIFT_JOURNAL",
    "DemoUserDefinition",
    "RoleDefinition",
    "UserAccount",
    "UserSession",
    "get_accessible_tabs",
    "get_permissions_for_role",
    "get_role_definitions",
    "has_permission",
    "hash_password",
]
